name = "discord-dice-roll-bot"
main = "./src/server.js"
compatibility_date="2024-04-04"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID

[[d1_databases]]
binding = "DB"
database_name = "d1-main-db"
database_id = "b097a061-2b4c-4272-9aeb-e68214501cc5"

# wrangler.toml (wrangler v3.79.0^)
[observability]
enabled = true
head_sampling_rate = 1